### ISSUE TITLE
Trouble with authenticating to S3

### ISSUE THREAD

**Issue by pabau** [robinpellegrims/pellegrims#285]
Hi first of all I am so grateful for the fact this plugin exists as open source. I am trying to install it..

**Describe the bug**
I set the AWS_PROFILE and check `aws s3 ls` works as expected. However I see this output

```

@aws-sdk/credential-provider-node - defaultProvider::fromEnv WARNING:
    Multiple credential sources detected: 
    Both AWS_PROFILE and the pair AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY static credentials are set.
    This SDK will proceed with the AWS_PROFILE value.
    
    However, a future version may change this behavior to prefer the ENV static credentials.
    Please ensure that your environment only sets either the AWS_PROFILE or the
    AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY pair.
------------------------------------------------------------------------------
Warning: Failed to check if cache file exists in S3
File: 17456133250912078476.tar.gz
Error: Could not load credentials from any providers
------------------------------------------------------------------------------
CredentialsProviderError: Could not load credentials from any providers
    at /opt/atlassian/pipelines/agent/build/node_modules/@pellegrims/nx-remotecache-s3/node_modules/@aws-sdk/credential-provider-node/dist-cjs/index.js:136:13
    at /opt/atlassian/pipelines/agent/build/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async coalesceProvider (/opt/atlassian/pipelines/agent/build/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
    at async /opt/atlassian/pipelines/agent/build/node_modules/@smithy/property-provider/dist-cjs/index.js:142:18 {
  tryNextLink: false
}
```

**To Reproduce**
```
  "tasksRunnerOptions": {
    "default": {
      "runner": "@pellegrims/nx-remotecache-s3",
      "options": {
        "cacheableOperations": [
          "prebuild-docker",
          "lint",
          "integration",
          "build",
          "build-docker",
          "tsc",
          "test",
          "e2e"
        ],
        "verbose": true,
        "bucket": "nx-remote-cache",
        "prefix": "${BITBUCKET_BRANCH}/",
        "region": "eu-west-2",
        "profile": "default",
        "forcePathStyle": true
      }
    }
  }
```

**Additional context**
I am new to the concept of Remote Caching when it comes to Nx.

**Comment by robinpellegrims** [comment]
Thank you for reporting this bug. 
Can you give some more information, like the version of nx and of this package that you are using?
